{% set version = "1.2.4" %}

package:
  name: nifty
  version: {{ version }}

source:
  url: https://github.com/DerThorsten/nifty/archive/v{{ version }}.tar.gz
  sha256: 0984b0fa97c7517aa303ba66a507f7cd0403177d6bc7ec12cc8acb8e7bc08acf

build:
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - xtensor >=0.26,<0.27
    - xtensor-python >=0.28,<0.29
    - libboost-devel
    - libvigra
    # Vigra Numpy is used at link time too
    - vigra
    - z5py >=2.0.20
    # build dependencies needed for z5
    - nlohmann_json
    - blosc
    - bzip2
    - zlib
  run:
    - python
    - numpy >=1.22
    - scikit-image
    - vigra

test:
  imports:
    - nifty
    - nifty.graph
    - nifty.distributed  # [not win]
  source_files:
    - src/python/test/**/*.py
  commands:
    - python -m unittest discover -s src/python/test -v
  requires:
    - z5py

about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  license_file: LICENSE
  summary: nifty

extra:
  recipe-maintainers:
    - constantinpape
    - DerThorsten
